'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const routes=read('backend/src/modules/almacen/almacen.routes.js');
const controller=read('backend/src/modules/almacen/almacen.controller.js');
const service=read('backend/src/modules/almacen/almacen.service.js');
const frontend=read('modules/almacen/almacen.js');
const css=read('modules/almacen/almacen.css').toLowerCase();
assert(routes.includes("router.get('/auditoria/catalogos'"));
assert(routes.includes("router.get('/auditoria/muestra'"));
assert(!routes.includes("router.post('/auditoria"));
assert(routes.includes('OPERATIONS_PERMISSION'));
assert(controller.includes('service.getAuditCatalogs()'));
assert(controller.includes('service.getAuditSample(req.query||{})'));
assert(service.includes('async function getAuditCatalogs()'));
assert(service.includes('async function getAuditSample(query)'));
const auditBlock=service.split('// [Aster | 2026-08-30 | ALMACEN-AUDITORIA-AIVEN-V002]')[1].split('module.exports = {')[0];
assert(!/\b(INSERT|UPDATE|DELETE|REPLACE|TRUNCATE|DROP|ALTER|CREATE)\b/i.test(auditBlock));
assert(auditBlock.includes("tipo_registro='${RECORD_TYPES.INVENTORY}'"));
assert(auditBlock.includes('COALESCE(fisico,0) > 0'));
assert(frontend.includes("'/api/almacen/auditoria/catalogos'"));
assert(frontend.includes("'/api/almacen/auditoria/muestra'"));
assert(frontend.includes("view.dataset.almacenReady='4-v002';"));
assert(!frontend.includes('localStorage'));
assert(!frontend.includes('Pend. Información'));
assert(frontend.includes('Sin persistencia'));
assert(!css.includes('transform:scale('));
assert(!css.includes('zoom:'));
assert(!fs.existsSync(path.join(ROOT,'sql')));
console.log('OK fase4_auditoria_static');
