const repository=require('./ventas-clientes-contactos.repository');
const clientesRepository=require('../ventas-clientes/ventas-clientes.repository');
const ventasVisibility=require('../ventas/ventas-visibility.service');
function err(code,msg){const e=new Error(msg);e.statusCode=code;return e;}function pos(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:null;}function text(v,max){if(v===undefined||v===null)return null;const s=String(v).trim();return s?(max?s.slice(0,max):s):null;}function actor(ctx){const id=pos(ctx?.user?.id_SB);if(!id)throw err(401,'Sesión requerida.');return id;}
async function assertClient(connection,idCliente,ctx){const scope=await ventasVisibility.resolveVisibilityScope(connection,ctx);const row=await clientesRepository.findById(connection,idCliente,{scope,actorId:actor(ctx)});if(!row)throw err(404,'Cliente no encontrado o fuera de tu alcance.');return row;}
async function assertContact(connection,idCliente,idContacto,ctx){await assertClient(connection,idCliente,ctx);const row=await repository.findById(connection,idContacto);if(!row||Number(row.id_cliente)!==idCliente)throw err(404,'Contacto no encontrado o fuera del cliente.');return row;}
async function list(idRaw,ctx){const id=pos(idRaw);if(!id)throw err(400,'id_cliente inválido.');const c=await repository.getConnection();try{const cliente=await assertClient(c,id,ctx);let contactos=await repository.listByClient(c,id);if(contactos.length===0&&text(cliente?.nombre_contacto,200)){await c.beginTransaction();try{const idContacto=await repository.insert(c,{id_cliente:id,nombre_contacto:text(cliente.nombre_contacto,200),puesto_contacto:text(cliente.puesto_contacto,150),email:text(cliente.email,200),telefono:text(cliente.telefono,80),contacto_principal:1,activo:1,created_by:actor(ctx),updated_by:actor(ctx)});await c.commit();const contacto=await repository.findById(c,idContacto);contactos=contacto?[contacto]:[];}catch(e){await c.rollback();throw e;}}return{ok:true,source:'aiven',contactos,data:contactos};}finally{c.release();}}
async function create(idRaw,payload,ctx){const id=pos(idRaw);if(!id)throw err(400,'id_cliente inválido.');const nombre=text(payload?.nombre_contacto,200);if(!nombre)throw err(400,'nombre_contacto es obligatorio.');const c=await repository.getConnection();try{await c.beginTransaction();await assertClient(c,id,ctx);if(Number(payload?.contacto_principal)===1)await repository.unsetPrincipal(c,id);const idContacto=await repository.insert(c,{id_cliente:id,nombre_contacto:nombre,puesto_contacto:text(payload?.puesto_contacto,150),email:text(payload?.email,200),telefono:text(payload?.telefono,80),contacto_principal:Number(payload?.contacto_principal)===1?1:0,activo:1,created_by:actor(ctx),updated_by:actor(ctx)});const contacto=await repository.findById(c,idContacto);await c.commit();return{ok:true,source:'aiven',message:'Contacto creado correctamente.',contacto};}catch(e){await c.rollback();throw e;}finally{c.release();}}
async function update(idRaw,contactRaw,payload,ctx){const id=pos(idRaw),cid=pos(contactRaw);if(!id||!cid)throw err(400,'Identificadores inválidos.');const c=await repository.getConnection();try{await c.beginTransaction();const current=await assertContact(c,id,cid,ctx);const data={};if(Object.prototype.hasOwnProperty.call(payload,'nombre_contacto')){data.nombre_contacto=text(payload.nombre_contacto,200);if(!data.nombre_contacto)throw err(400,'nombre_contacto es obligatorio.');}if(Object.prototype.hasOwnProperty.call(payload,'puesto_contacto'))data.puesto_contacto=text(payload.puesto_contacto,150);if(Object.prototype.hasOwnProperty.call(payload,'email'))data.email=text(payload.email,200);if(Object.prototype.hasOwnProperty.call(payload,'telefono'))data.telefono=text(payload.telefono,80);if(Object.prototype.hasOwnProperty.call(payload,'contacto_principal')){data.contacto_principal=Number(payload.contacto_principal)===1?1:0;if(data.contacto_principal===1)await repository.unsetPrincipal(c,id);}data.updated_by=actor(ctx);await repository.update(c,cid,data);await c.commit();return{ok:true,source:'aiven',contacto:await repository.findById(c,cid),anterior:current.id_contacto};}catch(e){await c.rollback();throw e;}finally{c.release();}}
async function setPrincipal(idRaw,contactRaw,ctx){const id=pos(idRaw),cid=pos(contactRaw);if(!id||!cid)throw err(400,'Identificadores inválidos.');const c=await repository.getConnection();try{await c.beginTransaction();await assertContact(c,id,cid,ctx);await repository.unsetPrincipal(c,id);await repository.update(c,cid,{contacto_principal:1,updated_by:actor(ctx)});await c.commit();return{ok:true,source:'aiven',id_contacto:cid,contacto_principal:true};}catch(e){await c.rollback();throw e;}finally{c.release();}}
async function remove(idRaw,contactRaw,ctx){const id=pos(idRaw),cid=pos(contactRaw);if(!id||!cid)throw err(400,'Identificadores inválidos.');const c=await repository.getConnection();try{await c.beginTransaction();await assertContact(c,id,cid,ctx);await repository.softDelete(c,cid,actor(ctx));await c.commit();return{ok:true,source:'aiven',id_contacto:cid,eliminado:true};}catch(e){await c.rollback();throw e;}finally{c.release();}}
module.exports={list,create,update,setPrincipal,remove};
