const express = require('express');

const healthRoutes = require('../modules/health/health.routes');
const authRoutes = require('./auth.routes');
const dataRoutes = require('./data.routes');
const supportRoutes = require('./support.routes');
const usuariosRoutes = require('./usuarios.routes');
const catalogosRoutes = require('./catalogos.routes');
const devRoutes = require('./dev.routes');
const logisticaRoutes = require('./logistica.routes');
const usuariosRelAdminRoutes = require('./usuarios-rel-admin.routes');
const insFlRoutes = require('./ins-fl.routes');
const panelControlRoutes = require('./panel-control.routes');
const googleRoutes = require('./google.routes');
const googleDriveRoutes = require('./google-drive.routes');
const instalacionesDriveRoutes = require('../modules/instalaciones-drive/instalaciones-drive.routes');
const instalacionesProyectoDriveRoutes = require('../modules/instalaciones-proyecto-drive/instalaciones-proyecto-drive.routes');
const instalacionesComentariosJuntaRoutes = require('../modules/instalaciones-comentarios-junta/instalaciones-comentarios-junta.routes');
const ventasDashboardRoutes = require('../modules/ventas-dashboard/ventas-dashboard.routes');
const ventasCotizacionesRoutes = require('../modules/ventas-cotizaciones/ventas-cotizaciones.routes');
const ventasCotizacionesHistorialRoutes = require('../modules/ventas-cotizaciones-historial/ventas-cotizaciones-historial.routes');
const ventasClientesRoutes = require('../modules/ventas-clientes/ventas-clientes.routes');
const ventasClientesContactosRoutes = require('../modules/ventas-clientes-contactos/ventas-clientes-contactos.routes');
const ventasProspeccionRoutes = require('../modules/ventas-prospeccion/ventas-prospeccion.routes');
const ventasRedesRoutes = require('../modules/ventas-redes/ventas-redes.routes');
const pushNotificationsRoutes = require('../modules/push-notifications/push-notifications.routes');
const devicePermissionsRoutes = require('../modules/device-permissions/device-permissions.routes');
const catalogoGeneralRoutes = require('../modules/catalogo-general/catalogo-general.routes');
const azureStorageRoutes = require('../modules/azure-storage/azure-storage.routes');
const experimentalAtencionPrioritariaRoutes = require('../modules/experimental-atencion-prioritaria/experimental-atencion-prioritaria.routes');
const experimentalResumenDiaRoutes = require('../modules/experimental-resumen-dia/experimental-resumen-dia.routes');

const router = express.Router();

router.use(healthRoutes);
router.use('/auth', authRoutes);
router.use('/support', supportRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/catalogos', catalogosRoutes);
router.use('/dev', devRoutes);
router.use('/logistica', logisticaRoutes);
router.use('/ins-fl', insFlRoutes);
router.use('/usuarios-rel-admin', usuariosRelAdminRoutes);
router.use('/panel-control', panelControlRoutes);
router.use('/google', googleRoutes);
router.use('/google/drive', googleDriveRoutes);
router.use('/instalaciones', instalacionesDriveRoutes);
router.use('/instalaciones', instalacionesProyectoDriveRoutes);
router.use('/instalaciones', instalacionesComentariosJuntaRoutes);
router.use('/ventas', ventasDashboardRoutes);
router.use('/ventas', ventasCotizacionesHistorialRoutes);
router.use('/ventas', ventasCotizacionesRoutes);
router.use('/ventas', ventasClientesRoutes);
router.use('/ventas', ventasClientesContactosRoutes);
router.use('/ventas', ventasProspeccionRoutes);
router.use('/ventas', ventasRedesRoutes);
router.use('/push', pushNotificationsRoutes);
router.use('/device-permissions', devicePermissionsRoutes);
router.use('/catalogo-general', catalogoGeneralRoutes);
router.use('/azure-storage', azureStorageRoutes);
router.use('/experimental', experimentalAtencionPrioritariaRoutes);
router.use('/experimental', experimentalResumenDiaRoutes);
router.use(dataRoutes);

module.exports = router;
