'use strict';

const express = require('express');
const controller = require('./dashboard-callcenter.controller');
const { humanInformationGuard_gnral } = require('../../middleware/information-access-gnral.middleware');

const router = express.Router();

const DASHBOARD_CALL_CENTER_READ_PERMISSIONS = Object.freeze([
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_CAUSA_FALLA_BLT.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_CAUSA_FALLA_CLIENTE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_ESTADO_TICKETS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_POR_ESTADO_DE_LA_REPUBLICA.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_POR_TIPO_DE_EQUIPO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_RESPONSABILIDAD.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_GRAFICAS_TICKETS_POR_ZONA_OPERATIVA.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_ABIERTOS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_ATRAPADOS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_CERRADOS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_EN_CRITICOS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_EN_CURSO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_FILTRACIONES.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_FUERA_DE_SLA.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_NO_FUNCIONANDO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_PROM_CIERRE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_PROM_LLEGADA.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_PROM_MTBC_ANO_ACTUAL.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_PROM_MTBC_U365.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_RESP_BLT.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_RESP_CLIENTE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_TICEKTS_CERRADOS_SIN_RESPONSABLE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_TICEKTS_SIN_RESPONSABLE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_TICKETS.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_KPI_VOLTAJE.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_TABLA_EQUIPOS_EQUIPOS_CON_MAS_LLAMADAS_DEL_PERIODO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_TABLA_PROYECTOS_PROYECTOS_CON_MAS_LLAMADAS_DEL_PERIODO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_TABLA_TICKETS_TICKETS_DEL_PERIODO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_U365D_LLAMADAS_U365D_EQUIPO.VER',
  'OPERACION_DASHBOARD_CALL_CENTER_U365D_LLAMADAS_U365D_PROYECTO.VER',
]);

const dashboardCallCenterInitialGuard_uni = humanInformationGuard_gnral({
  permissionCodesAny: DASHBOARD_CALL_CENTER_READ_PERMISSIONS,
  domain: 'UNITED',
  groupingCode: 'OPERACION'
});

router.get(
  '/operacion/dashboard-call-center/inicial',
  ...dashboardCallCenterInitialGuard_uni,
  controller.getInitialData
);

module.exports = router;
