'use strict';
const express=require('express');
const controller=require('./logistica-produccion.controller');
const {requireAuth}=require('../../middleware/auth.middleware');
const {createUploadMiddleware_gnral}=require('../../middleware/storage-upload.middleware');
const upload=createUploadMiddleware_gnral({fieldName:'archivo',required:true,maxFiles:1,maxFileMb:25,policyName:'GENERAL'});
const router=express.Router();
router.use(requireAuth);
router.get('/opciones-ppns',controller.options);
router.get('/documentos/faltantes',controller.missingDocuments);
router.get('/documentos',controller.documents);
router.get('/pvo/completos',controller.pvoComplete);
router.get('/pvo/faltantes',controller.pvoMissing);
router.get('/',controller.list);
router.post('/',controller.create);
router.get('/:id',controller.detail);
router.patch('/:id',controller.update);
router.get('/:id/archivos',controller.files);
router.post('/:id/archivos',upload,controller.upload);
router.patch('/:id/archivos/:idArchivo',upload,controller.replaceFile);
router.delete('/:id/archivos/:idArchivo',controller.removeFile);
router.get('/:id/comentarios',controller.comments);
router.post('/:id/comentarios',controller.addComment);
router.patch('/:id/comentarios/:idComentario',controller.editComment);
router.delete('/:id/comentarios/:idComentario',controller.removeComment);
module.exports=router;
