'use strict';

const repo = require('./logistica-produccion.repository');
const storage = require('../../services/storage/azure-storage.service');

function error(message,status=400,code='VALIDATION_ERROR'){const e=new Error(message);e.status=status;e.statusCode=status;e.code=code;return e;}
function positive(value,name){const n=Number(value);if(!Number.isInteger(n)||n<1)throw error(`${name} inválido.`);return n;}
function hasDate(value){const s=String(value||'').trim();return /^\d{4}-\d{2}-\d{2}/.test(s)&&!Number.isNaN(Date.parse(s.slice(0,10)+'T00:00:00Z'));}
function validPpns(value){const s=String(value||'').trim().toUpperCase();return Boolean(s&&!['SIN PP NS','SIN PPNS','N/A'].includes(s));}
function isoWeekAtMexico(date=new Date()){
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).reduce((a,p)=>(a[p.type]=p.value,a),{});
  const d=new Date(Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day)));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);
  const year=d.getUTCFullYear();const start=new Date(Date.UTC(year,0,1));return {anio:year,semana:Math.ceil((((d-start)/86400000)+1)/7)};
}
function weekLabel(value){if(!hasDate(value))return null;const d=new Date(String(value).slice(0,10)+'T00:00:00Z');const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=d.getUTCFullYear();const start=new Date(Date.UTC(y,0,1));return {anio:y,semana:Math.ceil((((d-start)/86400000)+1)/7)};}
function split(value){return String(value||'').split(',').map(v=>v.trim()).filter(Boolean);}
function decorate(row){
  const ppns=row.id_ppns||row.ppns_referencia||'';const saleDates=split(row.fechas_venta);
  const indicators=[];if(Number(row.cpvo_count)===0)indicators.push({codigo:'FALTA_ARCHIVO_PVO',emoji:'📍',nombre:'Falta Archivo PVO'});
  if(!validPpns(ppns))indicators.push({codigo:'FALTA_PPNS',emoji:'🥨',nombre:'Falta PPNS'});
  if(Number(row.archivos_count)===0)indicators.push({codigo:'FALTAN_DOCS_PROD',emoji:'💾',nombre:'Faltan Docs de Prod',regla:'PROVISIONAL_AL_MENOS_UN_ARCHIVO'});
  return {...row,ppns,proyecto:row.proyecto||row.proyecto_referencia||'',indicadores:indicators,
    instalaciones:{supervisores:split(row.supervisores),asesores:split(row.asesores),fechas_pvo_fl:split(row.fechas_pvo_fl),fechas_cubos:split(row.fechas_cubos),
      conflictos:{supervisor:Number(row.supervisores_count)>1,asesor:Number(row.asesores_count)>1,pvo_fl:Number(row.pvo_fl_count)>1,cubos:Number(row.cubos_count)>1}},
    venta:{estado:saleDates.length>1?'AMBIGUO':saleDates.length===1?'UNICA':'SIN_VENTA',fechas_candidatas:saleDates,semana:saleDates.length===1?weekLabel(saleDates[0]):null},
    pvo:{cpvo:Number(row.cpvo_count)>0,pvo_log:hasDate(row.fecha_pvo),pvo_fl:split(row.fechas_pvo_fl).some(hasDate)}};
}
async function list(query){return {ok:true,data:(await repo.list(query)).map(decorate),reglas:{documentos:'PROVISIONAL_AL_MENOS_UN_ARCHIVO'}};}
async function detail(id){const row=await repo.byId(positive(id,'id'));if(!row)throw error('Registro de Producción no encontrado.',404);const decorated=decorate(row);return {ok:true,data:{produccion:decorated,logistica:{id_log_ops:row.id_log_ops,ppns:decorated.ppns,proyecto:decorated.proyecto,fecha_pvo:row.fecha_pvo,estatus:row.estatus_logistica},instalaciones:decorated.instalaciones,venta:decorated.venta,archivos:await listFiles(id),comentarios:await repo.comments(id),indicadores:decorated.indicadores}};}
async function options(query){return {ok:true,data:await repo.ppnsOptions(query.q),catalogo_estatus:await repo.statuses()};}
async function create(input,user){const idLog=positive(input.id_log_ops,'id_log_ops');const comentario=String(input.comentario||'').trim();if(comentario.length>5000)throw error('El comentario excede 5000 caracteres.');const period=isoWeekAtMexico();const id=await repo.create({id_log_ops:idLog,id_estatus_produccion:input.id_estatus_produccion,comentario,semana:period.semana,anio:period.anio},positive(user.id_SB||user.id,'usuario'));return detail(id);}
async function update(id,input,user){const allowed=['id_estatus_produccion','fecha_envio_docs_fabrica','fecha_envio_pago_fabrica'];const unknown=Object.keys(input).filter(k=>!allowed.includes(k));if(unknown.length)throw error(`Campos no editables: ${unknown.join(', ')}.`);for(const key of allowed.slice(1)){if(input[key]&&!hasDate(input[key]))throw error(`${key} debe ser una fecha válida.`);}const current=(await detail(id)).data.produccion;const payload={id_estatus_produccion:Object.hasOwn(input,'id_estatus_produccion')?input.id_estatus_produccion:current.id_estatus_produccion,fecha_envio_docs_fabrica:Object.hasOwn(input,'fecha_envio_docs_fabrica')?input.fecha_envio_docs_fabrica:current.fecha_envio_docs_fabrica,fecha_envio_pago_fabrica:Object.hasOwn(input,'fecha_envio_pago_fabrica')?input.fecha_envio_pago_fabrica:current.fecha_envio_pago_fabrica};if(!(await repo.update(positive(id,'id'),payload,positive(user.id_SB||user.id,'usuario'))))throw error('Registro de Producción no encontrado.',404);return detail(id);}
async function listFiles(id){const rows=await repo.files(positive(id,'id'));return Promise.all(rows.map(async row=>{if(row.storage_provider==='LEGACY_URL')return {...row,url_acceso:row.storage_url};if(!row.storage_blob_name)return {...row,url_acceso:null};try{const sas=await storage.createReadSas_gnral(row.storage_blob_name,{containerName:row.storage_container,fileName:row.nombre_original});return {...row,url_acceso:sas.url,url_expira:sas.expires_at};}catch(_e){return {...row,url_acceso:null,storage_no_disponible:true};}}));}
function fileSlot(type,slot){const t=String(type||'').trim().toUpperCase();const n=positive(slot,'numero_archivo');if(!['CPVO','GM'].includes(t)||(t==='CPVO'&&n>2)||(t==='GM'&&n>10))throw error('Slot de archivo inválido. CPVO admite 1..2 y GM 1..10.');return {type:t,slot:n};}
function validateUploadPolicy(file){const maxMb=25;if(Number(file.size)>maxMb*1024*1024)throw error(`El archivo excede el límite de ${maxMb} MB.`,413,'FILE_TOO_LARGE');}
async function upload(id,input,file,user){if(!file)throw error('Selecciona un archivo.');validateUploadPolicy(file);id=positive(id,'id');await detail(id);const {type,slot}=fileSlot(input.tipo_archivo,input.numero_archivo);const existing=(await repo.files(id)).find(x=>x.tipo_archivo===type&&Number(x.numero_archivo)===slot);const uploaded=await storage.uploadPrivate_gnral({file,empresa:'CORELLIAN',modulo:'logistica-produccion',entidadTipo:'produccion',entidadId:id,subruta:type.toLowerCase(),metadata:{uploaded_by:user.id_SB||user.id,tipo:type,slot}});try{await repo.upsertFile(id,type,slot,uploaded,positive(user.id_SB||user.id,'usuario'));}catch(e){await storage.deleteBlob_gnral(uploaded.storage_blob_name,{containerName:uploaded.storage_container,queueOnFailure:true}).catch(()=>null);throw e;}if(existing&&existing.storage_provider==='AZURE_BLOB'&&existing.storage_blob_name!==uploaded.storage_blob_name)await storage.deleteBlob_gnral(existing.storage_blob_name,{containerName:existing.storage_container,queueOnFailure:true,queueContext:{modulo:'logistica-produccion',entidadTipo:'archivo',entidadId:existing.id_archivo,solicitadoPor:user.id_SB||user.id}}).catch(()=>null);return {ok:true,data:await listFiles(id)};}
async function replaceFile(id,fileId,file,user){id=positive(id,'id');const current=await repo.fileById(id,positive(fileId,'idArchivo'));if(!current||!current.activo)throw error('Archivo no encontrado.',404);return upload(id,{tipo_archivo:current.tipo_archivo,numero_archivo:current.numero_archivo},file,user);}
async function removeFile(id,fileId,user){id=positive(id,'id');fileId=positive(fileId,'idArchivo');const row=await repo.fileById(id,fileId);if(!row||!row.activo)throw error('Archivo no encontrado.',404);if(!(await repo.deactivateFile(id,fileId,positive(user.id_SB||user.id,'usuario'))))throw error('Archivo no encontrado.',404);if(row.storage_provider==='AZURE_BLOB'&&row.storage_blob_name)await storage.deleteBlob_gnral(row.storage_blob_name,{containerName:row.storage_container,queueOnFailure:true,queueContext:{modulo:'logistica-produccion',entidadTipo:'archivo',entidadId:fileId,solicitadoPor:user.id_SB||user.id}}).catch(()=>null);return {ok:true,data:await listFiles(id)};}
async function addComment(id,input,user){id=positive(id,'id');await detail(id);const text=String(input.comentario||'').trim();if(!text||text.length>5000)throw error('El comentario debe contener entre 1 y 5000 caracteres.');await repo.addComment(id,text,input.id_comentario_padre?positive(input.id_comentario_padre,'id_comentario_padre'):null,positive(user.id_SB||user.id,'usuario'));return {ok:true,data:await repo.comments(id)};}
async function editComment(id,cid,input,user){const text=String(input.comentario||'').trim();if(!text||text.length>5000)throw error('El comentario debe contener entre 1 y 5000 caracteres.');if(!(await repo.updateComment(positive(id,'id'),positive(cid,'idComentario'),text,positive(user.id_SB||user.id,'usuario'))))throw error('Comentario no encontrado o no pertenece al usuario.',404);return {ok:true,data:await repo.comments(id)};}
async function removeComment(id,cid,user){if(!(await repo.deleteComment(positive(id,'id'),positive(cid,'idComentario'),positive(user.id_SB||user.id,'usuario'))))throw error('Comentario no encontrado o no pertenece al usuario.',404);return {ok:true,data:await repo.comments(id)};}
async function documents(query,missing=false){const rows=(await repo.list(query)).map(decorate);if(missing)return {ok:true,data:rows.filter(r=>Number(r.archivos_count)===0),regla:'PROVISIONAL_AL_MENOS_UN_ARCHIVO'};const out=[];for(const row of rows)for(const file of await listFiles(row.id_produccion))out.push({...file,id_produccion:row.id_produccion,proyecto:row.proyecto,ppns:row.ppns});return {ok:true,data:out};}
async function pvo(query,missing=false){const rows=(await repo.list(query)).map(decorate);return {ok:true,data:rows.filter(r=>missing?!(r.pvo.cpvo&&r.pvo.pvo_log&&r.pvo.pvo_fl):(r.pvo.cpvo&&r.pvo.pvo_log&&r.pvo.pvo_fl))};}
module.exports={list,detail,options,create,update,listFiles,upload,replaceFile,removeFile,addComment,editComment,removeComment,documents,pvo,decorate,isoWeekAtMexico,fileSlot,validateUploadPolicy};
