'use strict';
// [Aster | 2026-09-01 | ASTER-MG | FIX REESTRUCTURACION LOGISTICA PRODUCCION V001]
const express=require('express');
const controller=require('./logistica-produccion.controller');
const {requireAuth}=require('../../middleware/auth.middleware');
const {createUploadMiddleware_gnral}=require('../../middleware/storage-upload.middleware');
const upload=createUploadMiddleware_gnral({fieldName:'archivo',required:true,maxFiles:1,maxFileMb:25,policyName:'GENERAL'});
const router=express.Router();
router.use(requireAuth);
router.get('/opciones-ppns',controller.options);
router.get('/manual/catalogos',controller.manualCatalogs);
router.get('/manual/proyectos-vendidos',controller.manualProjects);
router.get('/manual/asesores',controller.manualAdvisors);
router.get('/manual/supervisores',controller.manualSupervisors);
router.get('/manual/ppns',controller.manualPpns);
router.get('/documentos/faltantes',controller.missingDocuments);
router.get('/documentos',controller.documents);
router.get('/pvo/completos',controller.pvoComplete);
router.get('/pvo/faltantes',controller.pvoMissing);
router.get('/',controller.list);
router.post('/',controller.create);
router.get('/:id',controller.detail);
router.patch('/:id',controller.update);
router.get('/:id/archivos',controller.files);
router.post('/:id/archivos',upload,controller.upload);
router.patch('/:id/archivos/:idArchivo',upload,controller.replaceFile);
router.delete('/:id/archivos/:idArchivo',controller.removeFile);
module.exports=router;
